### ISSUE TITLE
Native cloud providers with GCP and AWS python lib

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/fabfed#60] opened 2023-07-12 18:23 UTC
The goal is to connect to a user provided VPC from the stitching point. 

- [x] should experiment with AWS and GCP python client. Try use the python code (with some test cases) to attach an existing AWS VPC to a DirectConnect service or GCP VPC to a (creating) VlanAttachment.
- [x] will be adding such native AWS/GCP provider to fabfed with @abessiari 's help.

**Comment by xi-yang** [comment] 2023-07-20 14:55
@zlion (July 24-Aug 11) experiment with AWS and GCP python client. Try use the python code (with some test cases) to attach an existing AWS VPC to a DirectConnect service or GCP VPC to a (creating) VlanAttachment. 

Next step (late Aug) will be adding such native AWS/GCP provider to fabfed with @abessiari 's help.

**Comment by zlion** [comment] 2023-07-20 16:37
Sure, I got it.

**Comment by abessiari** [comment] 2023-07-27 05:53
@zlion 

For aws we may want to look at AWS SDK for Python (Boto3). 

https://boto3.amazonaws.com/v1/documentation/api/latest/index.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/directconnect.html

**Comment by zlion** [comment] 2023-07-31 15:22
Initial versions of python scripts that add given VPC to direct connect(AWS) and interconnect(GCP) have been checked into branch "develop-lzhang9" and  PR#65 has been created.

**Comment by zlion** [comment] 2023-08-17 21:05
Verified that the GCP provider creates and destroys the network resource as expected. There is one thing I missed in the sample code that the "pairing key" should be read out and passed to Fabric provider. Good job @abessiari .

**Comment by abessiari** [comment] 2023-08-17 21:07
Yes I will have that part ready for you sometime tomorrow. Thanks.

**Comment by zlion** [comment] 2023-08-17 21:35
There are some issues when creating a slice in the RENCI site. It could result from bugs in fablib according to Komal preliminary investigation.

1. Failed to create Al2s network with the Notebook testing script "create_al2s.ipynb"

2. Failed to print the facilityport,

```
Exception: 'FacilityPort' object has no attribute 'get_node'
Traceback (most recent call last):
  File "/tmp/ipykernel_152/2316175781.py", line 52, in <module>
    print(f"facility_port_iface {fabric_facility_port_iface}")
  File "/opt/conda/lib/python3.10/site-packages/fabrictestbed_extensions/fablib/interface.py", line 82, in __str__
    if self.get_network():
  File "/opt/conda/lib/python3.10/site-packages/fabrictestbed_extensions/fablib/interface.py", line 678, in get_network
    for net in self.get_slice().get_networks():
  File "/opt/conda/lib/python3.10/site-packages/fabrictestbed_extensions/fablib/interface.py", line 649, in get_slice
    return self.get_node().get_slice()
  File "/opt/conda/lib/python3.10/site-packages/fabrictestbed_extensions/fablib/interface.py", line 658, in get_node
    return self.get_component().get_node()
AttributeError: 'FacilityPort' object has no attribute 'get_node'
```

**Comment by zlion** [comment] 2023-08-18 03:20
I came across an issue when submitting a slicet: "Couldnt create VRF: Couldnt create Endpoint: Couldnt find an available Unit." as shown below. Already opened a ticket to Internet2 to start the investigation.

`failed lease update- all units failed priming: Exception during create for unit: ef3a16c9-be74-4032-864e-45eab3a72045 (PlaybookException(Playbook has failed tasks: results: None, error_text: Couldnt create VRF: Couldnt create Endpoint: Couldnt find an available Unit., error: 1), [(core1.loui.net.internet2.edu, HundredGigE0/0/0/24), (agg4.ashb.net.internet2.edu, Bundle-Ether5)])#all units failed priming: Exception during create for unit: ef3a16c9-be74-4032-864e-45eab3a72045 (PlaybookException(Playbook has failed tasks: results: None, error_text: Couldnt create VRF: Couldnt create Endpoint: Couldnt find an available Unit., error: 1), [(core1.loui.net.internet2.edu, HundredGigE0/0/0/24), (agg4.ashb.net.internet2.edu, Bundle-Ether5)])#`

There are two interface resources to be allocated: "core1.loui" and "agg4.ashb". The latter one can be controlled via input parameters to the method facility_port(). But the former one is automatically/dynamically  picked up by the process between Fabric and Internet2.

**Comment by zlion** [comment] 2023-08-18 13:28
@abessiari @xi-yang 

Investigated the above issue with the AMHandler/test_oess_handler.py and found
1. the "oess_handler.py" works as expected.
2. the problem is related to the "VLAN tag", i.e. changing VLAN tag fixes the problem.

Further thoughts:
As the method "add_facility_port()" automatically pick up the tag from an internal pool, take into consideration,
1. how to pick up a valid VLAN tag from the pool?
2. need to retry with different tag if previous one fails with errors "Could not find an available Unit"

**Comment by zlion** [comment] 2023-08-28 21:48
Another case of "VRF not found".

Check the log files on al2sam shown below indicates that he VLAN 3500 on the endpoint core1.wash is already in used.
[nrig-service@al2sam ~]$ cd ControlFramework/fabric_cf/authority/al2s-am/
[nrig-service@al2sam al2s-am]$ ls -ltr logs/*-handler.log

`https://al2s.net.internet2.edu/oess-service-basic/vrf.cgi?method=provision&name=MySlice-al2s-3-296256999979&description=MySlice-al2s-3-296256999979&local_asn=55038&workgroup_id=1482&endpoint=%7B%22node%22%3A%20%22core1.wash.net.internet2.edu%22%2C%20%22bandwidth%22%3A%200%2C%20%22interface%22%3A%20%22HundredGigE0/0/0/28%22%2C%20%22tag%22%3A%20%223500%22%2C%20%22jumbo%22%3A%201%2C%20%22cloud_account_id%22%3A%20null%2C%20%22entity%22%3A%20%22al2s%22%2C%20%22peers%22%3A%20%5B%7B%22bfd%22%3A%200%2C%20%22ip_version%22%3A%20%22ipv4%22%2C%20%22peer_ip%22%3A%20%22192.168.50.2/24%22%2C%20%22peer_asn%22%3A%20%22398900%22%2C%20%22local_ip%22%3A%20%22192.168.50.1/24%22%2C%20%22md5_key%22%3A%20%22secret%22%7D%5D%7D&endpoint=%7B%22node%22%3A%20%22agg4.ashb.net.internet2.edu%22%2C%20%22bandwidth%22%3A%201000%2C%20%22interface%22%3A%20%22HundredGigE0/0/0/7%22%2C%20%22tag%22%3A%20%22101%22%2C%20%22jumbo%22%3A%201%2C%20%22cloud_account_id%22%3A%20%22296256999979%22%2C%20%22entity%22%3A%20%22al2s%22%2C%20%22peers%22%3A%20%5B%7B%22bfd%22%3A%200%2C%20%22ip_version%22%3A%20%22ipv4%22%2C%20%22peer_ip%22%3A%20%22192.168.30.2/24%22%2C%20%22peer_asn%22%3A%20%2264512%22%2C%20%22local_ip%22%3A%20%22192.168.30.1/24%22%2C%20%22md5_key%22%3A%20%220xzsEwC7xk6c1fK_h.xHyAdx%22%7D%5D%7D`

**Comment by zlion** [comment] 2023-08-29 21:19
Komal submitted a request on the the algorithm changes regarding the VLAN issue.

https://fabric-testbed.atlassian.net/browse/FIP-714
Change Broker Allocation Algorithm to spread resources across available hosts more evenly as opposed to first fit.

**Comment by zlion** [comment] 2023-09-11 03:29
AWS
====
Found an issue with the method "find_available_dx_connection()" described as follows:
In one test case,  a connection is ordered but an exception is raised from this method. The reason is that multiple connections might have the same name but one is in state "deleted", which ends up with timeout exception.

A fix is committed and ready for reviewing. 

GCP
===
Tested with Fabfed that workflow is created successfully and the GCP VMs can be reached from the Fabric node via ping and ssh.

**Comment by xi-yang** [comment] 2023-09-13 21:02
One observation I had with the AWS provider is that it would not work with a VPC that already had a routing table created with subnets being associated to.

The fabfed provider would create a separate routing table and VGW which is disconnected with the existing routing table. 

A better flow would be:
1) check if a VPC has a VGW associated; if so, use that VGW to associate with the DX VIF. Otherwise, create and associate a VGW. 
2) check if a VPC has an existing main routing table. If so enable route propagation to the VGW with this existing routing table. Otherwise, create a new routing table and enable the propagation (also prompt a warning message that users need to associate any existing subnets to this routing table)

**Closed** 2023-09-28 17:27 UTC
